"""Effect creation, queries, and duration ticking."""

from __future__ import annotations

from .status_effects import (
    SKILL_ENERGY_COST_ALL,
    add_warmup_stacks,
    adjust_skill_energy_cost,
    apply_burn_stacks,
    apply_freeze_stacks,
    apply_infusion,
    apply_poison_stacks,
    apply_skill_energy_cost_increase,
    count_buff_effects,
    get_burn_effects,
    get_freeze_effect,
    get_freeze_stacks,
    get_poison_effect,
    get_poison_stacks,
    get_skill_energy_cost_adjustments,
    get_total_burn_stacks,
    get_warmup_effect,
    get_warmup_stacks,
    has_infusion,
    is_action_blocked,
    is_debuff_immune,
    is_stunned,
    make_effect,
    purge_debuffs,
    purge_random_buff,
    purge_random_buffs,
    tick_effects,
    tick_warmup_stacks,
)

__all__ = [
    "SKILL_ENERGY_COST_ALL",
    "add_warmup_stacks",
    "adjust_skill_energy_cost",
    "apply_burn_stacks",
    "apply_freeze_stacks",
    "apply_infusion",
    "apply_poison_stacks",
    "apply_skill_energy_cost_increase",
    "count_buff_effects",
    "get_burn_effects",
    "get_freeze_effect",
    "get_freeze_stacks",
    "get_poison_effect",
    "get_poison_stacks",
    "get_skill_energy_cost_adjustments",
    "get_total_burn_stacks",
    "get_warmup_effect",
    "get_warmup_stacks",
    "has_infusion",
    "is_action_blocked",
    "is_debuff_immune",
    "is_stunned",
    "make_effect",
    "purge_debuffs",
    "purge_random_buff",
    "purge_random_buffs",
    "tick_effects",
    "tick_warmup_stacks",
]
