"""Static spirit templates."""

from __future__ import annotations

from typing import Dict, List, Optional

from ..battle.types import (
    BaseStats,
    PassiveSkillDef,
    SkillDef,
    SpiritTemplate,
    TargetType,
)

FLORA = SpiritTemplate(
    id="flora",
    name="蹦蹦种子",
    description="蹦蹦种子",
    base_stats=BaseStats(hp=700, atk=100, mag_atk=120, def_=130, mag_def=130, speed=120),
    passive_skill=PassiveSkillDef(
        id="flora_passive",
        name="紧急支援",
        description=(
            "某个己方精灵血量低于30%时，立刻为其回复（100%自身魔攻）点血量，"
            "净化其所有负面效果并提升其25%速度（1回合）。每局对战最多触发一次。"
        ),
    ),
    normal_attack=SkillDef(
        id="flora_normal",
        name="普通攻击",
        description="对一个敌方场上精灵造成（100%自身物攻）点物理伤害。",
        cooldown=0,
        target_type=TargetType.single_enemy,
        launches_attack=True,
    ),
    skills=[
        SkillDef(
            id="flora_skill1",
            name="光合作用",
            description="为一个己方精灵回复（80%自身魔攻）点血量；若目标是自身，则额外解除随机一个负面效果。",
            cooldown=0,
            target_type=TargetType.single_ally,
            energy_cost=2,
        ),
        SkillDef(
            id="flora_skill2",
            name="抗逆",
            description="使一个己方精灵获得20%减伤，持续2回合。",
            cooldown=0,
            target_type=TargetType.single_ally,
            energy_cost=2,
        ),
        SkillDef(
            id="flora_skill3",
            name="麻醉",
            description="对敌方所有精灵造成（50%自身魔攻）点魔法伤害，并降低10%速度（2回合）。",
            cooldown=0,
            target_type=TargetType.all_enemies,
            energy_cost=3,
            launches_attack=True,
        ),
    ],
)

CLAWDRAGON = SpiritTemplate(
    id="clawdragon",
    name="上古战龙",
    description="上古战龙",
    base_stats=BaseStats(hp=550, atk=150, mag_atk=100, def_=110, mag_def=100, speed=140),
    passive_skill=PassiveSkillDef(
        id="clawdragon_passive",
        name="守护者",
        description=(
            "受到伤害时，提升自身15%物防与魔防，持续2回合。"
            "此效果每回合最多触发1次，自身回合开始时重置次数。"
        ),
    ),
    normal_attack=SkillDef(
        id="clawdragon_normal",
        name="普通攻击",
        description="对一个敌方精灵造成（100%自身物攻）点物理伤害。",
        cooldown=0,
        target_type=TargetType.single_enemy,
        launches_attack=True,
    ),
    skills=[
        SkillDef(
            id="clawdragon_skill1",
            name="传说力量",
            description="对一个敌方精灵造成一段（50%自身物攻+10%目标当前生命值）点物理伤害。",
            cooldown=0,
            target_type=TargetType.single_enemy,
            energy_cost=2,
            launches_attack=True,
        ),
        SkillDef(
            id="clawdragon_skill2",
            name="龙之舞",
            description="提高自身20%物攻与20%速度。",
            cooldown=0,
            target_type=TargetType.self,
            energy_cost=3,
        ),
        SkillDef(
            id="clawdragon_skill3",
            name="过肩摔",
            description="对一个敌方精灵造成（120%自身物攻）点物理伤害，并使其眩晕1回合。",
            cooldown=0,
            target_type=TargetType.single_enemy,
            energy_cost=4,
            launches_attack=True,
        ),
    ],
)

PARSAS = SpiritTemplate(
    id="parsas",
    name="帕尔萨斯",
    description="帕尔萨斯",
    base_stats=BaseStats(hp=650, atk=130, mag_atk=100, def_=120, mag_def=120, speed=120),
    passive_skill=PassiveSkillDef(
        id="parsas_passive",
        name="收藏灵魂",
        description=(
            "自身技能固定不消耗能量。对局开始时获得2点秘能，秘能上限为20点。"
            "自身成为普攻或技能的唯一目标时，回复2点秘能。"
            "当自身秘能从小于13点增长至大于等于13点时，使自身下回合提前100%，"
            "并使自身的「恐怖」效果延长1回合。"
        ),
    ),
    normal_attack=SkillDef(
        id="parsas_normal",
        name="普通攻击",
        description="对一个敌方精灵造成（100%自身物攻）点物理伤害，并回复1点秘能。",
        cooldown=0,
        target_type=TargetType.single_enemy,
        launches_attack=True,
    ),
    skills=[
        SkillDef(
            id="parsas_skill1",
            name="恶魔契约",
            description="消耗自身当前生命值的10%，回复3点秘能。",
            cooldown=0,
            target_type=TargetType.self,
            energy_cost=None,
        ),
        SkillDef(
            id="parsas_skill2",
            name="巨魔之眼",
            description=(
                "秘能不少于7点时可以使用。消耗7点秘能，赋予自身「恐怖」效果，"
                "持续3回合，期间再次赋予此效果会重置持续时间；"
                "然后对一个敌方精灵造成（120%自身魔攻）点魔法伤害。"
                "（恐怖：正面效果。携带者造成伤害时，无视10%的魔防。）"
            ),
            cooldown=0,
            target_type=TargetType.single_enemy,
            energy_cost=7,
            launches_attack=True,
        ),
        SkillDef(
            id="parsas_skill3",
            name="新月乱舞",
            description=(
                "秘能不少于13点时可以使用。消耗13点秘能，"
                "对一个敌方精灵造成（120%自身魔攻）点魔法伤害，"
                "随后对全体敌方精灵造成（80%自身魔攻）点魔法伤害。"
            ),
            cooldown=0,
            target_type=TargetType.single_enemy,
            energy_cost=13,
            launches_attack=True,
        ),
    ],
)

CHAOSLING = SpiritTemplate(
    id="chaosling",
    name="梦想龙",
    description="梦想龙",
    base_stats=BaseStats(hp=600, atk=140, mag_atk=100, def_=120, mag_def=120, speed=130),
    passive_skill=PassiveSkillDef(
        id="chaosling_passive",
        name="梦想潮汐",
        description="行动后随机获得一项正面效果和一项负面效果（物攻/魔攻/物防/魔防/速度的提升或降低10%）。自身受到的所有伤害降低（2% * 自身负面效果数，最高10%）。",
    ),
    normal_attack=SkillDef(
        id="chaosling_normal",
        name="普通攻击",
        description="对一个敌方精灵造成（100%自身物攻）点物理伤害。",
        cooldown=0,
        target_type=TargetType.single_enemy,
        launches_attack=True,
    ),
    skills=[
        SkillDef(
            id="chaosling_skill1",
            name="愿力凝聚",
            description="蓄力3回合：每回合提升自身10%物攻；第一、二、三回合分别降低自身10%魔攻、10%物防、10%魔防。再次释放此技能会打断蓄力。",
            cooldown=0,
            target_type=TargetType.self,
            energy_cost=3,
        ),
        SkillDef(
            id="chaosling_skill2",
            name="精神风暴",
            description="对敌方所有精灵造成（60%自身物攻）点物理伤害。",
            cooldown=0,
            target_type=TargetType.all_enemies,
            energy_cost=2,
            launches_attack=True,
        ),
        SkillDef(
            id="chaosling_skill3",
            name="命运逆转",
            description="反转自身所有能力值降低类型的负面效果，然后对一个敌方精灵造成（150%自身物攻）点物理伤害。",
            cooldown=0,
            target_type=TargetType.single_enemy,
            energy_cost=4,
            launches_attack=True,
        ),
    ],
)

STARWEAVER = SpiritTemplate(
    id="starweaver",
    name="黑猫巫师",
    description="黑猫巫师",
    base_stats=BaseStats(hp=550, atk=100, mag_atk=110, def_=140, mag_def=140, speed=150),
    passive_skill=PassiveSkillDef(
        id="starweaver_passive",
        name="共振",
        description=(
            "自身技能固定不消耗能量。秘能上限为8点。对局开始时获得4点秘能。"
            "队友对敌方目标发动攻击时，若自身拥有不少于1点秘能，则消耗1点秘能"
            "对随机一个目标造成40点固伤附加伤害。"
        ),
    ),
    normal_attack=SkillDef(
        id="starweaver_normal",
        name="普通攻击",
        description="对一个敌方精灵造成（100%自身物攻）点物理伤害。",
        cooldown=0,
        target_type=TargetType.single_enemy,
        launches_attack=True,
    ),
    skills=[
        SkillDef(
            id="starweaver_skill1",
            name="汲取",
            description="对敌方所有精灵造成（20%自身魔攻）点魔法伤害，然后获得（敌方精灵数量）点秘能。",
            cooldown=0,
            target_type=TargetType.all_enemies,
            energy_cost=0,
            launches_attack=True,
        ),
        SkillDef(
            id="starweaver_skill2",
            name="净化",
            description="秘能不少于4点时可使用。消耗4点秘能，净化一个己方精灵的所有负面效果，并使其免疫负面效果（2回合）。",
            cooldown=0,
            target_type=TargetType.single_ally,
            energy_cost=4,
        ),
        SkillDef(
            id="starweaver_skill3",
            name="星爆",
            description="消耗全部秘能，对敌方场上所有精灵造成（40 + 5 * 消耗秘能数）点固伤，然后使自己眩晕2回合并获得4点秘能。",
            cooldown=0,
            target_type=TargetType.all_enemies,
            energy_cost=-1,
            launches_attack=True,
        ),
    ],
)

STEAMDRAGON = SpiritTemplate(
    id="steamdragon",
    name="蒸汽神龙",
    description="蒸汽神龙",
    base_stats=BaseStats(hp=700, atk=130, mag_atk=100, def_=140, mag_def=120, speed=100),
    passive_skill=PassiveSkillDef(
        id="steamdragon_passive",
        name="热启动",
        description="自身回合开始时，获得2层升温。",
    ),
    normal_attack=SkillDef(
        id="steamdragon_normal",
        name="普通攻击",
        description="对一个敌方精灵造成（50%自身物攻）点物理伤害，对其相邻精灵造成（25%×自身物攻）点物理伤害。",
        cooldown=0,
        target_type=TargetType.single_enemy,
        launches_attack=True,
    ),
    skills=[
        SkillDef(
            id="steamdragon_skill1",
            name="烙印",
            description="对一个敌方场上精灵造成（50%自身物攻）点物理伤害，然后给予其5层灼烧。",
            cooldown=0,
            target_type=TargetType.single_enemy,
            energy_cost=2,
            launches_attack=True,
        ),
        SkillDef(
            id="steamdragon_skill2",
            name="嗜热",
            description="回复自身（敌方场上所有精灵灼烧层数之和 * 8）点血量。",
            cooldown=0,
            target_type=TargetType.self,
            energy_cost=2,
        ),
        SkillDef(
            id="steamdragon_skill3",
            name="沸腾",
            description="消耗自身（25%自身生命上限）点生命，获得4层升温。",
            cooldown=0,
            target_type=TargetType.self,
            energy_cost=0,
        ),
    ],
)

QIUKA = SpiritTemplate(
    id="qiuka",
    name="裘卡",
    description="裘卡",
    base_stats=BaseStats(hp=500, atk=150, mag_atk=100, def_=110, mag_def=120, speed=150),
    passive_skill=PassiveSkillDef(
        id="qiuka_passive",
        name="痛苦",
        description="造成伤害时，若目标有中毒，此次伤害提升30%。",
    ),
    normal_attack=SkillDef(
        id="qiuka_normal",
        name="普通攻击",
        description="对一个敌方精灵造成（100%自身物攻）点物理伤害。",
        cooldown=0,
        target_type=TargetType.single_enemy,
        launches_attack=True,
    ),
    skills=[
        SkillDef(
            id="qiuka_skill1",
            name="毒刺",
            description="能量 3。重复7次：对敌方随机目标造成（20%自身物攻）点物理伤害，并赋予1层中毒。",
            cooldown=0,
            target_type=TargetType.all_enemies,
            energy_cost=3,
            launches_attack=True,
        ),
        SkillDef(
            id="qiuka_skill2",
            name="厉毒",
            description="能量 2。指定一名敌方精灵，赋予3层中毒并使其触发一次中毒效果。",
            cooldown=0,
            target_type=TargetType.single_enemy,
            energy_cost=2,
        ),
        SkillDef(
            id="qiuka_skill3",
            name="毒爪",
            description=(
                "能量 3。对一名敌方精灵造成（100%自身物攻）点物理伤害；"
                "目标每层中毒使此次伤害倍率+15%自身物攻，最多计入10层。"
            ),
            cooldown=0,
            target_type=TargetType.single_enemy,
            energy_cost=3,
            launches_attack=True,
        ),
    ],
)

FANYING = SpiritTemplate(
    id="fanying",
    name="凡鹰",
    description="凡鹰",
    base_stats=BaseStats(hp=550, atk=130, mag_atk=100, def_=110, mag_def=130, speed=140),
    passive_skill=PassiveSkillDef(
        id="fanying_passive",
        name="破风",
        description="开局获得破风：自身速度+8%，相邻己方精灵速度+4%。",
    ),
    normal_attack=SkillDef(
        id="fanying_normal",
        name="普通攻击",
        description="对一个敌方精灵造成（100%自身物攻）点物理伤害。",
        cooldown=0,
        target_type=TargetType.single_enemy,
        launches_attack=True,
    ),
    skills=[
        SkillDef(
            id="fanying_skill1",
            name="气旋",
            description="能量 1。对一名敌方精灵造成（80%自身物攻）点物理伤害并降低15%速度（1回合）；对相邻槽位敌方造成（40%自身物攻）点物理伤害。",
            cooldown=0,
            target_type=TargetType.single_enemy,
            energy_cost=1,
            launches_attack=True,
        ),
        SkillDef(
            id="fanying_skill2",
            name="羽翼守护",
            description="能量 2。清除我方所有羽翼守护，再指定一名己方精灵获得羽翼守护（速度+8%，受伤时下一回合提前5%）。",
            cooldown=0,
            target_type=TargetType.single_ally,
            energy_cost=2,
        ),
        SkillDef(
            id="fanying_skill3",
            name="该你上场了",
            description="能量 3。指定场上精灵，使其下一回合提前100%；若为友方则获得20%伤害提升（1回合），若为敌方则眩晕1回合。",
            cooldown=0,
            target_type=TargetType.any_on_field,
            energy_cost=3,
        ),
    ],
)

TITA = SpiritTemplate(
    id="tita",
    name="缇塔",
    description="缇塔",
    base_stats=BaseStats(hp=750, atk=100, mag_atk=100, def_=140, mag_def=110, speed=100),
    passive_skill=PassiveSkillDef(
        id="tita_passive",
        name="缓存",
        description="若我方精灵在一回合内消耗不少于5点能量，回合结束时回复1点能量。",
    ),
    normal_attack=SkillDef(
        id="tita_normal",
        name="普通攻击",
        description="对一个敌方精灵造成（100%自身物攻）点物理伤害。",
        cooldown=0,
        target_type=TargetType.single_enemy,
        launches_attack=True,
    ),
    skills=[
        SkillDef(
            id="tita_skill1",
            name="分流",
            description="能量 5。获得2层分流；若已有分流则置为2层（友方回合结束后回复1能量，自身回合开始减1层）。",
            cooldown=0,
            target_type=TargetType.self,
            energy_cost=5,
        ),
        SkillDef(
            id="tita_skill2",
            name="扩容",
            description="能量 5。获得1层扩容（最多5层，使己方能量上限提升对应点数）。",
            cooldown=0,
            target_type=TargetType.self,
            energy_cost=5,
        ),
        SkillDef(
            id="tita_skill3",
            name="过载",
            description="能量 3。对一名敌方精灵造成（175%自身魔攻）点魔法伤害，并使双方速度降低30%（1回合）。",
            cooldown=0,
            target_type=TargetType.single_enemy,
            energy_cost=3,
            launches_attack=True,
        ),
    ],
)

CUIDING = SpiritTemplate(
    id="cuiding",
    name="翠顶夫人",
    description="翠顶夫人",
    base_stats=BaseStats(hp=700, atk=100, mag_atk=100, def_=130, mag_def=130, speed=140),
    passive_skill=PassiveSkillDef(
        id="cuiding_passive",
        name="澄净",
        description="治疗我方精灵时，若其有浸润效果则回复1点能量，否则赋予其浸润（1回合）。",
    ),
    normal_attack=SkillDef(
        id="cuiding_normal",
        name="普通攻击",
        description="对一个敌方精灵造成（100%自身物攻）点物理伤害。",
        cooldown=0,
        target_type=TargetType.single_enemy,
        launches_attack=True,
    ),
    skills=[
        SkillDef(
            id="cuiding_skill1",
            name="暖流",
            description="能量 3。指定一名己方精灵，为其与相邻精灵回复（10%自身最大生命）点生命。",
            cooldown=0,
            target_type=TargetType.single_ally_on_field,
            energy_cost=3,
        ),
        SkillDef(
            id="cuiding_skill2",
            name="涟漪",
            description="能量 3。对敌方全体造成（8%自身最大生命）点魔法伤害，并随机驱散其各一个正面效果。",
            cooldown=0,
            target_type=TargetType.all_enemies,
            energy_cost=3,
            launches_attack=True,
        ),
        SkillDef(
            id="cuiding_skill3",
            name="共舞",
            description="能量 5。为我方全体回复（10%自身最大生命）点生命；然后使除自身外的队友立刻获得一次额外行动（按队伍编号顺序），并使全体下一回合延后50%。",
            cooldown=0,
            target_type=TargetType.all_allies,
            energy_cost=5,
        ),
    ],
)

GUIFASHI = SpiritTemplate(
    id="guifashi",
    name="诡法师",
    description="以牌库与额外行动征战的策士。",
    base_stats=BaseStats(hp=600, atk=100, mag_atk=130, def_=130, mag_def=130, speed=110),
    passive_skill=PassiveSkillDef(
        id="guifashi_passive",
        name="塔罗",
        description="开局加入11种大阿卡纳各1张。每回合开始抽3张，回合结束将所有手牌洗回牌堆。",
    ),
    normal_attack=SkillDef(
        id="guifashi_normal",
        name="普通攻击",
        description="对一个敌方精灵造成（100%自身物攻）点物理伤害。",
        cooldown=0,
        target_type=TargetType.single_enemy,
        launches_attack=True,
    ),
    skills=[
        SkillDef(
            id="guifashi_draw",
            name="占卜",
            description="能量 1。从牌堆随机抽1张牌；然后可再行动一次（占卜/揭晓/逆位/跳过）。",
            cooldown=0,
            target_type=TargetType.self,
            energy_cost=1,
        ),
        SkillDef(
            id="guifashi_show",
            name="揭晓",
            description="能量 1。打出1张手牌并触发牌面效果；然后可再行动一次（占卜/揭晓/逆位/跳过）。",
            cooldown=0,
            target_type=TargetType.any_on_field,
            energy_cost=1,
        ),
        SkillDef(
            id="guifashi_cheat",
            name="逆位",
            description="能量 2。将一张手牌变为指定的另一种阿卡纳牌；然后可再行动一次（占卜/揭晓/逆位/跳过）。",
            cooldown=0,
            target_type=TargetType.self,
            energy_cost=2,
        ),
    ],
)

XIAOZONG = SpiritTemplate(
    id="xiaozong",
    name="小琮",
    description="以灵气护体、濒死通灵的灵珏之灵。",
    base_stats=BaseStats(hp=600, atk=110, mag_atk=140, def_=120, mag_def=130, speed=110),
    passive_skill=PassiveSkillDef(
        id="xiaozong_passive",
        name="灵珏御光",
        description=(
            "灵珏护体：受到每段伤害时，降低（10%自身灵气层数，向下取整）点伤害，并赋予自身本段实际减少的伤害值层灵气。"
            "自身死亡时，若尚无通灵且有灵气层数，则将生命续至（自身灵气层数）点并获得通灵。"
            "通灵状态：受到每段伤害时，降低（10%自身灵气层数，向下取整）点伤害。"
            "灵气上限为对战开始时的生命上限。"
        ),
    ),
    normal_attack=SkillDef(
        id="xiaozong_normal",
        name="普通攻击",
        description=(
            "对一个敌方精灵造成（100%自身物攻）点物理伤害。"
            "通灵状态：消耗30层灵气，改为造成（100%自身魔攻）点魔法伤害。"
        ),
        cooldown=0,
        target_type=TargetType.single_enemy,
        launches_attack=True,
    ),
    skills=[
        SkillDef(
            id="xiaozong_skill1",
            name="日月齐光",
            description=(
                "能量 3。对一个敌方场上精灵造成（80%自身魔攻）点魔法伤害，对其相邻精灵造成（40%自身魔攻）点魔法伤害，并赋予自身30层灵气。"
                "通灵状态：消耗30层灵气，主目标改为（120%自身魔攻），相邻改为（60%自身魔攻），不再赋予灵气。"
            ),
            cooldown=0,
            target_type=TargetType.single_enemy,
            energy_cost=3,
            launches_attack=True,
        ),
        SkillDef(
            id="xiaozong_skill2",
            name="华采若英",
            description=(
                "能量 3。对一个敌方场上精灵造成（80%自身魔攻+20%自身灵气层数）点魔法伤害，并赋予自身30层灵气。"
                "通灵状态：消耗30层灵气，造成同样伤害并回复（30%此伤害值）点血量，不再赋予灵气。"
            ),
            cooldown=0,
            target_type=TargetType.single_enemy,
            energy_cost=3,
            launches_attack=True,
        ),
        SkillDef(
            id="xiaozong_skill3",
            name="远举云中",
            description=(
                "能量 3。获得10%减伤，并使日月齐光与华采若英的能量消耗减少1点，均持续3回合，"
                "期间再次使用本技能刷新持续时间；赋予自身30层灵气。"
                "通灵状态：消耗30层灵气，获得15%减伤，并使日月齐光与华采若英能量消耗减少1点，"
                "均持续3回合，期间再次使用本技能刷新持续时间。"
            ),
            cooldown=0,
            target_type=TargetType.self,
            energy_cost=3,
        ),
    ],
)

BAHAMUT = SpiritTemplate(
    id="bahamut",
    name="巴哈姆特",
    description="巴哈姆特",
    base_stats=BaseStats(hp=550, atk=140, mag_atk=100, def_=140, mag_def=140, speed=120),
    passive_skill=PassiveSkillDef(
        id="bahamut_passive",
        name="气蕴沧溟",
        description=(
            "战斗开始时，赋予自身10层“罡气”；"
            "若自身处于队伍首位，赋予自身“彻甲”；否则赋予自身“寸劲”。"
        ),
    ),
    normal_attack=SkillDef(
        id="bahamut_normal",
        name="普通攻击",
        description="对一个敌方精灵造成（100%自身物攻）点物理伤害。",
        cooldown=0,
        target_type=TargetType.single_enemy,
        launches_attack=True,
    ),
    skills=[
        SkillDef(
            id="bahamut_skill1",
            name="疾风拳",
            description="能量 1。对一个敌方精灵造成3段物理伤害，每段倍率为（50%自身物攻）。",
            cooldown=0,
            target_type=TargetType.single_enemy,
            energy_cost=1,
            launches_attack=True,
        ),
        SkillDef(
            id="bahamut_skill2",
            name="迎击",
            description="能量 1。获得1层“招架”。",
            cooldown=0,
            target_type=TargetType.self,
            energy_cost=1,
        ),
        SkillDef(
            id="bahamut_skill3",
            name="龙之舞",
            description="能量 3。永久提高自身20%物攻与20%速度。",
            cooldown=0,
            target_type=TargetType.self,
            energy_cost=3,
        ),
        SkillDef(
            id="bahamut_zhaojia_jiequan",
            name="截拳",
            description="消耗全部招架，对目标造成（招架层数）段物理伤害，每段（30%自身物攻）。",
            cooldown=0,
            target_type=TargetType.single_enemy,
            energy_cost=0,
            special=True,
            launches_attack=True,
        ),
        SkillDef(
            id="bahamut_zhaojia_fanpu",
            name="反扑",
            description=(
                "消耗全部招架，对目标造成（30%自身物攻）点物理伤害，"
                "然后重复（招架层数）次：对随机敌方造成（30%自身物攻）点物理伤害。"
            ),
            cooldown=0,
            target_type=TargetType.single_enemy,
            energy_cost=0,
            special=True,
            launches_attack=True,
        ),
    ],
)

DAERMAO = SpiritTemplate(
    id="daermao",
    name="大耳帽兜",
    description="以纯白净化与冰冻处决控场的霜系精灵。",
    base_stats=BaseStats(hp=600, atk=120, mag_atk=110, def_=140, mag_def=140, speed=120),
    passive_skill=PassiveSkillDef(
        id="daermao_passive",
        name="纯白",
        description=(
            "释放技能时，若目标的正面效果数为2或3，则随机清除其1个正面效果；"
            "若为4或更多，则随机清除其2个正面效果。"
        ),
    ),
    normal_attack=SkillDef(
        id="daermao_normal",
        name="普通攻击",
        description="对一个敌方精灵造成（100%自身物攻）点物理伤害。",
        cooldown=0,
        target_type=TargetType.single_enemy,
        launches_attack=True,
    ),
    skills=[
        SkillDef(
            id="daermao_skill1",
            name="轻雾",
            description="能量 2。使目标所有技能能耗+1，持续3回合；已有此效果时重置持续时间。",
            cooldown=0,
            target_type=TargetType.single_enemy,
            energy_cost=2,
        ),
        SkillDef(
            id="daermao_skill2",
            name="飞霰",
            description="能量 2。赋予目标6层冰冻，并赋予其相邻精灵3层冰冻（回合结束时生命不高于1%最大生命×层数则立刻阵亡）。",
            cooldown=0,
            target_type=TargetType.single_enemy,
            energy_cost=2,
        ),
        SkillDef(
            id="daermao_skill3",
            name="萌化",
            description="能量 4。使目标造成的伤害降低33%，持续2回合。",
            cooldown=0,
            target_type=TargetType.single_enemy,
            energy_cost=4,
        ),
    ],
)

HUXIAN = SpiritTemplate(
    id="huxian",
    name="尖嘴狐仙",
    description="尖嘴狐仙",
    base_stats=BaseStats(hp=500, atk=120, mag_atk=100, def_=140, mag_def=150, speed=140),
    passive_skill=PassiveSkillDef(
        id="huxian_passive",
        name="内爆",
        description=(
            "对敌方给予灼烧或中毒时（合并施加多层仍算 1 次）："
            "给予灼烧后触发该目标的中毒 1 次；给予中毒后触发该目标每个灼烧来源各 1 次。"
            "由内爆触发的结算不会再次触发内爆。"
        ),
    ),
    normal_attack=SkillDef(
        id="huxian_normal",
        name="普通攻击",
        description="对一个敌方精灵造成（100%自身物攻）点物理伤害。",
        cooldown=0,
        target_type=TargetType.single_enemy,
        launches_attack=True,
    ),
    skills=[
        SkillDef(
            id="huxian_skill1",
            name="烙印",
            description="对一个敌方精灵造成（50%自身物攻）点物理伤害，然后赋予其5层灼烧。",
            cooldown=0,
            target_type=TargetType.single_enemy,
            energy_cost=2,
            launches_attack=True,
        ),
        SkillDef(
            id="huxian_skill2",
            name="鬼火",
            description="对一个敌方精灵赋予4层中毒，然后赋予其4层灼烧。",
            cooldown=0,
            target_type=TargetType.single_enemy,
            energy_cost=3,
        ),
        SkillDef(
            id="huxian_skill3",
            name="扇风",
            description=(
                "对一个敌方精灵赋予4层灼烧，"
                "然后对其相邻敌方精灵各赋予（该目标灼烧层数一半，向下取整）层灼烧。"
            ),
            cooldown=0,
            target_type=TargetType.single_enemy,
            energy_cost=3,
        ),
    ],
)

SHENGYU = SpiritTemplate(
    id="shengyu",
    name="圣域祭司",
    description="圣域祭司",
    base_stats=BaseStats(hp=700, atk=120, mag_atk=130, def_=120, mag_def=120, speed=100),
    passive_skill=PassiveSkillDef(
        id="shengyu_passive",
        name="月盈",
        description=(
            "自身技能固定不消耗能量。秘能上限为5点。回合开始时获得5点秘能；"
            "回合结束时，消耗所有秘能，使自身速度提高（20*消耗秘能点数）点，持续2回合。"
            "己方精灵获得秘能后，使其额外获得1点秘能。"
        ),
    ),
    normal_attack=SkillDef(
        id="shengyu_normal",
        name="普通攻击",
        description="对一个敌方精灵造成（100%自身物攻）点物理伤害。",
        cooldown=0,
        target_type=TargetType.single_enemy,
        launches_attack=True,
    ),
    skills=[
        SkillDef(
            id="shengyu_skill1",
            name="圣洁",
            description=(
                "秘能不少于2点时可以使用。目标为一个己方精灵。"
                "消耗2点秘能，为目标回复（60%自身魔攻）点血量；"
                "若目标拥有秘能，则额外使其回复1点秘能。"
            ),
            cooldown=0,
            target_type=TargetType.single_ally,
            energy_cost=2,
        ),
        SkillDef(
            id="shengyu_skill2",
            name="指引",
            description=(
                "秘能不少于4点时可以使用。目标为一个敌方精灵。"
                "消耗4点秘能，使目标受到的伤害提高16%，持续3回合。"
            ),
            cooldown=0,
            target_type=TargetType.single_enemy,
            energy_cost=4,
        ),
        SkillDef(
            id="shengyu_skill3",
            name="再现",
            description=(
                "秘能不少于5点时可以使用。目标为一个敌方精灵。消耗5点秘能，"
                "将目标的随机一个能力值降低、造成伤害降低或受到伤害提高类型的负面效果"
                "（百分比或固定值）复制给除目标外的敌方所有精灵，"
                "以这种方式复制出的负面效果无法再次被复制。"
            ),
            cooldown=0,
            target_type=TargetType.single_enemy,
            energy_cost=5,
        ),
    ],
)

DEERLE = SpiritTemplate(
    id="deerle",
    name="梅花德尔勒",
    description="梅花德尔勒",
    base_stats=BaseStats(hp=600, atk=120, mag_atk=100, def_=130, mag_def=120, speed=140),
    passive_skill=PassiveSkillDef(
        id="deerle_passive",
        name="看破",
        description=(
            "战斗开始时，赋予随机两个敌方精灵「破绽」效果，持续3回合。"
            "对敌方目标释放普通攻击时，若目标拥有「破绽」，则清除其一条「破绽」"
            "（优先清除持续时间较短的「破绽」），并赋予除目标外随机两个敌方精灵"
            "「破绽」，持续3回合。（破绽：负面效果。物防降低5%。）"
        ),
    ),
    normal_attack=SkillDef(
        id="deerle_normal",
        name="普通攻击",
        description="对一个敌方精灵造成（100%自身物攻）点物理伤害。",
        cooldown=0,
        target_type=TargetType.single_enemy,
        launches_attack=True,
    ),
    skills=[
        SkillDef(
            id="deerle_skill1",
            name="剑花",
            description=(
                "目标为自身。若拥有「剑舞」，则将「剑舞」的持续时间重置为5回合，"
                "并叠加一层「剑舞」；否则获得1层「剑舞」，持续5回合。"
                "（剑舞：状态效果，可叠加，最多6层。每层提升5%物攻与20%速度；"
                "释放普通攻击后叠加一层「剑舞」，不重置持续时间。"
                "游戏开始时，获得1层「剑舞」，持续5回合。）"
            ),
            cooldown=0,
            target_type=TargetType.self,
            energy_cost=3,
        ),
        SkillDef(
            id="deerle_skill2",
            name="穿刺",
            description="对一个敌方精灵赋予「破绽」，持续3回合；然后对其造成（100%自身物攻）点物理伤害。",
            cooldown=0,
            target_type=TargetType.single_enemy,
            energy_cost=1,
            launches_attack=True,
        ),
        SkillDef(
            id="deerle_skill3",
            name="敏锐",
            description=(
                "对敌方所有精灵造成（25%自身物攻）点物理伤害；"
                "然后赋予所有拥有不少于3条「破绽」，且未拥有「漏洞百出」效果的目标「漏洞百出」。"
                "（漏洞百出：状态效果。施加者对持有者释放普通攻击时，"
                "施加者的此次普通攻击伤害提高25%，并获得一次额外行动；"
                "随后解除持有者的此效果。）"
            ),
            cooldown=0,
            target_type=TargetType.all_enemies,
            energy_cost=1,
            launches_attack=True,
        ),
    ],
)

TENGJIAO = SpiritTemplate(
    id="tengjiao",
    name="藤椒小巴",
    description="藤椒小巴",
    base_stats=BaseStats(hp=700, atk=140, mag_atk=100, def_=110, mag_def=110, speed=120),
    passive_skill=PassiveSkillDef(
        id="tengjiao_passive",
        name="热火朝天",
        description=(
            "我方精灵每消耗1点能量，积攒1层“火力”。当“火力”从小于10/20/30层增长至"
            "大于等于该层数时，分别获得一次额外行动：强制释放“出锅！”，菜品分别固定为"
            "“辣子鸡”/“水煮鱼”/“毛血旺”，此次不消耗能量。一次增长跨越多个阈值时各触发一次；"
            "须回落后再越过才会再次触发。"
        ),
    ),
    normal_attack=SkillDef(
        id="tengjiao_normal",
        name="普通攻击",
        description="对一个敌方精灵造成（100%自身物攻）点物理伤害。",
        cooldown=0,
        target_type=TargetType.single_enemy,
        launches_attack=True,
    ),
    skills=[
        SkillDef(
            id="tengjiao_skill1",
            name="浇油！",
            description="获得5层“火力”；提升自身20%物攻，持续3回合。",
            cooldown=0,
            target_type=TargetType.self,
            energy_cost=2,
        ),
        SkillDef(
            id="tengjiao_skill2",
            name="炝锅！",
            description=(
                "延长场上所有菜品效果（辣子鸡、水煮鱼、毛血旺）持续时间1回合，"
                "但不会超过该效果原本的持续时间。"
            ),
            cooldown=0,
            target_type=TargetType.self,
            energy_cost=2,
        ),
        SkillDef(
            id="tengjiao_skill3",
            name="出锅！",
            description=(
                "随机端出一道川菜：辣子鸡（点名己方，基于施加者物攻10%提升双攻，3回合）/"
                "水煮鱼（自身，基于携带者物攻10%提升全体己方含自身双攻，2回合）/"
                "毛血旺（全体敌方，消耗全部火力，每3层给予1层灼烧，并提高15%受到的持续伤害，3回合）。"
                "初始权重1:1:1；无水煮鱼时水煮鱼权重翻倍；火力≥20时毛血旺权重翻倍。"
                "辣子鸡需指定己方目标；水煮鱼与毛血旺无需点选。"
            ),
            cooldown=0,
            target_type=TargetType.none,
            energy_cost=3,
        ),
    ],
)

ALL_SPIRITS: List[SpiritTemplate] = [
    FLORA,
    CLAWDRAGON,
    PARSAS,
    CHAOSLING,
    STARWEAVER,
    STEAMDRAGON,
    QIUKA,
    FANYING,
    TITA,
    GUIFASHI,
    CUIDING,
    XIAOZONG,
    DAERMAO,
    BAHAMUT,
    HUXIAN,
    SHENGYU,
    DEERLE,
    TENGJIAO,
]

SPIRIT_BY_ID: Dict[str, SpiritTemplate] = {s.id: s for s in ALL_SPIRITS}

def get_spirit_template(sid: str) -> Optional[SpiritTemplate]:
    return SPIRIT_BY_ID.get(sid)
